# Generated by Django 4.2.30 on 2026-06-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='recurringhabit',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='timer',
        ),
        migrations.AddField(
            model_name='activitytimecalculate',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.goal'),
        ),
        migrations.AddField(
            model_name='activitytimecalculate',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.habit'),
        ),
        migrations.AddField(
            model_name='activitytimecalculate',
            name='recurring_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.recurringhabit'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tracker.status'),
        ),
    ]
