# Generated by Django 4.2.30 on 2026-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_goal_goal_type_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_hours',
            field=models.IntegerField(default=0),
        ),
    ]
