# Generated by Django 4.2.30 on 2026-07-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_goal_target_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
